[package]
name = "primitive-gpu"
version = "0.1.0"
edition = "2021"

[lib]
name = "primitive_gpu"
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
capi = []

[dependencies]
naga = { version = "24", features = ["wgsl-in"] }
wgpu = "24"
pollster = "0.4"
image = { version = "0.25", default-features = false, features = ["png"] }
anyhow = "1"
bytemuck = { version = "1", features = ["derive"] }

[profile.release]
lto = "thin"